services:
  prateek-db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Your_password123
    image: microsoft/mssql-server-linux
    ports:
      - "1435"
  prateek-socialback:
    build: ./Social-Back
    environment:
      SQLSERVER_HOST: Server=db;Database=PrateeksocialDBLinux;User=sa;Password=Your_password123
    links:
      - prateek-db
    ports:
      - "8080:5000"
version: "3"